### ISSUE TITLE
Could YTXAnimations can manual install?

### ISSUE THREAD

**Issue by hefangshi** [baidao/YTXAnimations#1]
I don't want to use pod since my project is a static library.

**Comment by mdsb100** [comment]
@hefangshi
I think you have to use pod in your project. Please try [pod-package](https://github.com/CocoaPods/cocoapods-packager) to package your static library like this:

```
pod package ${PROJECT_NAME}.podspec  --no-mangle --library --spec-sources=http://gitlab.baidao.com/ios/ytx-pod-specs.git,https://github.com/CocoaPods/Specs.git
```

By the why, do not use `--exclude-deps` options.

**Comment by hefangshi** [comment]
I copied the source code and add some include like UIKit and CoreGraphics, then it works fine :）
