### ISSUE TITLE
Import & Use in Swift

### ISSUE THREAD

**Issue by starsoheil2007** [baidao/YTXAnimations#4]
I install this library in pod by this : 
`pod 'YTXAnimations', :subspecs => ["AnimateCSS", "CSShake", "MagicCSS"]` 
I want using in swift , I try use with below line to import but not successfully : 
`
import YTXAnimations
//or
import AnimateCSS
//or
 import YTXAnimateCSS
`  

Please help me for use this library in swift . Tnx

**Comment by mdsb100** [comment]
Why closed?
Try this http://stackoverflow.com/questions/24002369/how-to-call-objective-c-code-from-swift

And try
```
pod 'YTXAnimaitons'
pod 'YTXAnimaitons/AnimateCSS'
```
